export enum RuoloIncarico {
    PROJECT_MANAGER="PROJECT_MANAGER",
	DELIVERY_MANAGER="DELIVERY_MANAGER", 
	ACCOUNT_MANAGER="ACCOUNT_MANAGER",
	QA_REVIEWER="QA_REVIEWER",
	RUOLO_GENERICO="RUOLO_GENERICO"
}